"""German vehicle-registration (Kfz-Kennzeichen) district codes -> geocodable
district / seat name. Used by the license-plate district anchor to turn the modal
plate prefix into a coarse location.

Not exhaustive (Germany has ~300 active codes) but covers all major cities/
districts nationwide and is dense around our test clips (Baden-Wurttemberg +
Bavarian Swabia, the Ulm region). Codes not present here simply don't vote.
Values are place names that geocode cleanly via Nominatim ("<name>, Germany").
"""

KFZ_DISTRICTS: dict[str, str] = {
    # --- city-states & major cities ---
    "B": "Berlin", "M": "München", "HH": "Hamburg", "K": "Köln",
    "F": "Frankfurt am Main", "S": "Stuttgart", "D": "Düsseldorf",
    "H": "Hannover", "N": "Nürnberg", "L": "Leipzig", "DD": "Dresden",
    "HB": "Bremen", "DO": "Dortmund", "E": "Essen", "DU": "Duisburg",
    "BO": "Bochum", "MA": "Mannheim", "KA": "Karlsruhe", "FR": "Freiburg",
    "HD": "Heidelberg", "WÜ": "Würzburg", "R": "Regensburg", "A": "Augsburg",
    "KS": "Kassel", "MZ": "Mainz", "W": "Wuppertal", "BN": "Bonn",
    "MS": "Münster", "AC": "Aachen", "BI": "Bielefeld", "KL": "Kaiserslautern",
    "SB": "Saarbrücken", "EF": "Erfurt", "MD": "Magdeburg", "RO": "Rosenheim",
    "KI": "Kiel", "HL": "Lübeck", "OS": "Osnabrück", "BS": "Braunschweig",
    "G": "Gera", "C": "Chemnitz", "J": "Jena", "P": "Potsdam", "FL": "Flensburg",
    "WI": "Wiesbaden", "OF": "Offenbach am Main", "DA": "Darmstadt",
    "GI": "Gießen", "MR": "Marburg", "FD": "Fulda", "HU": "Hanau",
    # --- Baden-Württemberg (our clip region) ---
    "UL": "Ulm", "BC": "Biberach an der Riß", "HDH": "Heidenheim an der Brenz",
    "GP": "Göppingen", "AA": "Aalen", "SIG": "Sigmaringen", "RV": "Ravensburg",
    "RT": "Reutlingen", "TÜ": "Tübingen", "ES": "Esslingen am Neckar",
    "BB": "Böblingen", "LB": "Ludwigsburg", "WN": "Waiblingen", "GÖ": "Göttingen",
    "HN": "Heilbronn", "KÜN": "Künzelsau", "SHA": "Schwäbisch Hall",
    "TBB": "Tauberbischofsheim", "HDB": "Eberbach", "MOS": "Mosbach",
    "PF": "Pforzheim", "CW": "Calw", "FDS": "Freudenstadt", "RW": "Rottweil",
    "VS": "Villingen-Schwenningen", "TUT": "Tuttlingen", "KN": "Konstanz",
    "ÜB": "Überlingen", "WT": "Waldshut-Tiengen", "LÖ": "Lörrach",
    "EM": "Emmendingen", "OG": "Offenburg", "BAD": "Baden-Baden",
    "RA": "Rastatt", "BL": "Balingen", "FN": "Friedrichshafen", "BT": "Bayreuth",
    # --- Bavaria, esp. Swabia (next to Ulm) ---
    "NU": "Neu-Ulm", "GZ": "Günzburg", "DLG": "Dillingen an der Donau",
    "MN": "Mindelheim", "KE": "Kempten", "OA": "Oberallgäu", "MM": "Memmingen",
    "DON": "Donauwörth", "AIC": "Aichach",
    "FDB": "Friedberg, Bayern",       # NOT the Hessian Friedberg (FB), 250 km away
    "LL": "Landsberg am Lech",
    "KF": "Kaufbeuren", "MOD": "Marktoberdorf", "SF": "Sonthofen",
    "IN": "Ingolstadt", "EI": "Eichstätt", "ND": "Neuburg an der Donau",
    "PA": "Passau", "LA": "Landshut", "DEG": "Deggendorf", "SR": "Straubing",
    "WM": "Weilheim", "GAP": "Garmisch-Partenkirchen", "MB": "Miesbach",
    "TÖL": "Bad Tölz", "FFB": "Fürstenfeldbruck", "DAH": "Dachau",
    "FS": "Freising", "ED": "Erding", "EBE": "Ebersberg", "STA": "Starnberg",
    "WÜM": "Waldmünchen", "AS": "Amberg", "SAD": "Schwandorf",
    "CHA": "Cham", "BGL": "Bad Reichenhall", "TS": "Traunstein", "MÜ": "Mühldorf am Inn",
    "AÖ": "Altötting", "RID": "Rottal-Inn", "FRG": "Freyung", "REG": "Regen",
    "KEH": "Kelheim", "NM": "Neumarkt in der Oberpfalz", "WEN": "Weiden",
    "BA": "Bamberg", "CO": "Coburg", "HO": "Hof", "KU": "Kulmbach",
    "LIF": "Lichtenfels", "FO": "Forchheim", "ER": "Erlangen",
    "FÜ": "Fürth", "AN": "Ansbach", "WUG": "Weißenburg", "RH": "Roth",
    "NEA": "Neustadt an der Aisch", "SW": "Schweinfurt", "HAS": "Haßfurt",
    "KG": "Bad Kissingen", "NES": "Bad Neustadt an der Saale", "MIL": "Miltenberg",
    "AB": "Aschaffenburg", "KT": "Kitzingen", "MSP": "Karlstadt",
    # --- NRW / Rhineland / other major districts ---
    "GE": "Gelsenkirchen", "HA": "Hagen", "HAM": "Hamm", "SO": "Soest",
    "PB": "Paderborn", "GT": "Gütersloh", "HF": "Herford", "MI": "Minden",
    "LIP": "Detmold", "HX": "Höxter", "OB": "Oberhausen", "MH": "Mülheim an der Ruhr",
    "RE": "Recklinghausen", "BOR": "Borken", "COE": "Coesfeld", "ST": "Steinfurt",
    "WAF": "Warendorf", "SU": "Siegburg", "GM": "Gummersbach", "BM": "Bergheim",
    "DN": "Düren", "EU": "Euskirchen", "HS": "Heinsberg", "VIE": "Viersen",
    "NE": "Neuss", "ME": "Mettmann", "SG": "Solingen", "RS": "Remscheid",
    "LEV": "Leverkusen", "KR": "Krefeld", "MG": "Mönchengladbach", "KLE": "Kleve",
    "WES": "Wesel", "SI": "Siegen", "OE": "Olpe", "MK": "Lüdenscheid",
    "EN": "Schwelm", "UN": "Unna", "HER": "Herne", "BOT": "Bottrop",
    # --- Hesse / RLP / Saarland ---
    "GG": "Groß-Gerau", "RÜD": "Rüdesheim am Rhein", "HG": "Bad Homburg",
    "FB": "Friedberg (Hessen)",       # NOT the Bavarian Friedberg (FDB)
    "LM": "Limburg an der Lahn", "WW": "Montabaur",
    "KO": "Koblenz", "NR": "Neuwied", "AK": "Altenkirchen", "SIM": "Simmern",
    "TR": "Trier", "WIL": "Wittlich", "BIT": "Bitburg", "DAU": "Daun",
    "LD": "Landau in der Pfalz", "SÜW": "Bad Bergzabern", "GER": "Germersheim",
    "SP": "Speyer", "FT": "Frankenthal", "LU": "Ludwigshafen", "NW": "Neustadt an der Weinstraße",
    "DÜW": "Bad Dürkheim", "KIB": "Kirchheimbolanden", "KH": "Bad Kreuznach",
    "AZ": "Alzey", "WO": "Worms", "BIR": "Birkenfeld", "NK": "Neunkirchen",
    "HOM": "Homburg", "SLS": "Saarlouis", "MZG": "Merzig", "WND": "St. Wendel",
    # --- North / East ---
    "OL": "Oldenburg", "EL": "Lingen (Ems)", "LER": "Leer", "AUR": "Aurich",
    "WHV": "Wilhelmshaven", "DEL": "Delmenhorst", "VEC": "Vechta", "CLP": "Cloppenburg",
    "DH": "Diepholz", "NI": "Nienburg", "VER": "Verden", "ROW": "Rotenburg (Wümme)",
    "STD": "Stade", "CUX": "Cuxhaven", "WL": "Winsen", "LG": "Lüneburg",
    "UE": "Uelzen", "CE": "Celle", "GF": "Gifhorn", "WOB": "Wolfsburg",
    "HI": "Hildesheim", "NOM": "Northeim", "HM": "Hameln", "HOL": "Holzminden",
    "SHG": "Stadthagen", "PE": "Peine", "SZ": "Salzgitter", "GS": "Goslar",
    "RZ": "Ratzeburg", "OD": "Bad Oldesloe", "SE": "Bad Segeberg", "PI": "Pinneberg",
    "IZ": "Itzehoe", "HEI": "Heide", "NF": "Husum", "SL": "Schleswig",
    "RD": "Rendsburg", "PLÖ": "Plön", "OH": "Eutin", "NMS": "Neumünster",
    "SN": "Schwerin", "HRO": "Rostock", "HGW": "Greifswald", "HST": "Stralsund",
    "MÜR": "Waren", "NB": "Neubrandenburg", "HWI": "Wismar",
    "HAL": "Halle", "DE": "Dessau", "WB": "Wittenberg",
    "SK": "Merseburg", "BLK": "Naumburg", "SLK": "Bernburg", "SDL": "Stendal",
    "EIC": "Heilbad Heiligenstadt", "NDH": "Nordhausen", "SÖM": "Sömmerda",
    "GTH": "Gotha", "SM": "Schmalkalden", "SHL": "Suhl", "SON": "Sonneberg",
    "SLF": "Saalfeld", "GRZ": "Greiz", "ABG": "Altenburg", "Z": "Zwickau",
    "V": "Plauen", "FG": "Freiberg", "PIR": "Pirna", "GR": "Görlitz",
    "BZ": "Bautzen", "MEI": "Meißen", "TDO": "Torgau", "LÖB": "Löbau",
    "BAR": "Eberswalde", "MOL": "Strausberg", "LOS": "Frankfurt (Oder)",
    "TF": "Luckenwalde", "PM": "Brandenburg an der Havel", "HVL": "Rathenow",
    "OPR": "Neuruppin", "PR": "Perleberg", "UM": "Prenzlau", "CB": "Cottbus",
    "SPN": "Spremberg", "EE": "Herzberg", "OHV": "Oranienburg",
}
